#pragma once

#define W32pServiceTableLimit_7601 453


static char *W32pServiceTableNames_7601[] = {
	"NtAcceptConnectPort"	,
	"NtAccessCheck"		,
	"NtAccessCheckAndAuditAlarm",
	"NtAccessCheckByType"		,
	"NtAccessCheckByTypeAndAuditAlarm"	,
	"NtAccessCheckByTypeResultList"	,
	"NtAccessCheckByTypeResultListAndAuditAlarm	"	,
	"NtAccessCheckByTypeResultListAndAuditAlarmByHandle"	,
//	"NtAcquireCrossVmMutant",
	"NtAcquireProcessActivityReference",
	"NtAddAtom"		,
	"NtAddAtomEx",
	"NtAddBootEntry"	,
	"NtAddDriverEntry"	,
	"NtAdjustGroupsToken"	,
	"NtAdjustPrivilegesToken"	,
	"NtAdjustTokenClaimsAndDeviceGroups",
	"NtAlertResumeThread"		,
	"NtAlertThreadByThreadId",                         
	"NtAllocateLocallyUniqueId"	,
	"NtAllocateReserveObject"	,
	"NtAllocateUserPhysicalPages"	,
	"NtAllocateUserPhysicalPagesEx",
	"NtAllocateUuids"				,
	"NtAllocateVirtualMemory"		,
	"NtAllocateVirtualMemoryEx",
	"NtAlpcAcceptConnectPort"	,
	"NtAlpcCancelMessage"	,
	"NtAlpcConnectPort"		,
	"NtAlpcConnectPortEx",
	"NtAlpcCreatePort"		,
	"NtAlpcCreatePortSection"		,
	"NtAlpcCreateResourceReserve"	,
	"NtAlpcCreateSectionView"		,
	"NtAlpcCreateSecurityContext"	,
	"NtAlpcDeletePortSection"		,
	"NtAlpcDeleteResourceReserve"	,
	"NtAlpcDeleteSectionView"		,
	"NtAlpcDeleteSecurityContext"	,
	"NtAlpcDisconnectPort"			,
	"NtAlpcImpersonateClientContainerOfPort",
	"NtAlpcImpersonateClientOfPort"		,
	"NtAlpcOpenSenderProcess"		,
	"NtAlpcOpenSenderThread"		,
	"NtAlpcQueryInformation"	,
	"NtAlpcQueryInformationMessage"		,
	"NtAlpcRevokeSecurityContext"	,
	"NtAlpcSendWaitReceivePort"		,
	"NtAlpcSetInformation"			,
	"NtAreMappedFilesTheSame" ,
	
	//"NtAssignProcessToJobObject"	,
	"NtAssociateWaitCompletionPacket",
	"NtCallEnclave",
	"NtCallbackReturn"		,
	//"NtCancelDeviceWakeupRequest",
	"NtCancelIoFile"		,
	"NtCancelIoFileEx"		,
	"NtCancelSynchronousIoFile"	,
	"NtCancelTimer"		,
	"NtCancelTimer2",
	"NtCancelWaitCompletionPacket",
	//"NtClearAllSavepointsTransaction",
	"NtClearEvent"			,
	//"NtClearSavepointTransaction",
	"NtClose"				,
	"NtCloseObjectAuditAlarm"	,
	"NtCommitComplete"		,
	"NtCommitEnlistment"	,
	"NtCommitTransaction"	,
	"NtCompactKeys	"		,
	"NtCompareTokens"		,
	"NtCompleteConnectPort"		,
	"NtCompressKey"		,
	"NtConnectPort"		,
	"NtContinue"		,
	//"NtContinueEx",
	"NtCreateDebugObject"	,
	"NtCreateDirectoryObject"	,
	"NtCreateDirectoryObjectEx",
	"NtCreateEnclave",
	"NtCreateEnlistment"	,
	//"NtCreateEvent"		,
	"NtCreateEventPair"		,
	//"NtCreateFile"		,
	"NtCreateIRTimer",
	"NtCreateIoCompletion"	,
	"NtCreateJobObject"			,
	"NtCreateJobSet"					,
	//"NtCreateKey"				,
	"NtCreateKeyTransacted"		,
	"NtCreateKeyedEvent"		,
	"NtCreateLowBoxToken",
	"NtCreateMailslotFile"		,
	"NtCreateMutant"		,
	"NtCreateNamedPipeFile"		,
	"NtCreatePagingFile"	,
	"NtCreatePartition",
	"NtCreatePort"			,
	"NtCreatePrivateNamespace"	,
	"NtCreateProcess"		,
	"NtCreateProcessEx"		,
	"NtCreateProfile"		,
	"NtCreateProfileEx"		,
	"NtCreateRegistryTransaction",
	"NtCreateResourceManager"	,
//	"NtCreateSectionEx",
	"NtCreateSemaphore"		,
	"NtCreateSymbolicLinkObject"	,
	"NtCreateThread	"		,
	"NtCreateThreadEx"		,
	"NtCreateTimer"		,
	"NtCreateToken"		,
	"NtCreateTokenEx",
	"NtCreateTransaction"	,
	"NtCreateTransactionManager",
	"NtCreateUserProcess"	,
	"NtCreateWaitablePort"		
	"NtCreateWorkerFactory"		,

	"NtDebugActiveProcess"	,
	"NtDebugContinue"		,
	"NtDelayExecution"	,
	"NtDeleteAtom"		,
	"NtDeleteBootEntry"	,
	"NtDeleteDriverEntry"	,
	"NtDeleteFile"		,
	"NtDeleteKey"			,
	"NtDeleteObjectAuditAlarm"		,
	"NtDeletePrivateNamespace"	,
	"NtDeleteValueKey"			,
	"NtDeviceIoControlFile"	,
	"NtDirectGraphicsCall",
	"NtDisableLastKnownGood"	,
	"NtDisplayString"	,
	"NtDrawText"		,
	"NtDuplicateObject"		,
	"NtDuplicateToken"		,
	"NtEnableLastKnownGood"		,
	"NtEnumerateBootEntries"	,
	"NtEnumerateDriverEntries"		,
	"NtEnumerateKey"				,
	"NtEnumerateSystemEnvironmentValuesEx"	,
	"NtEnumerateTransactionObject",
	"NtEnumerateValueKey"	,
	"NtExtendSection"		,
	"NtFilterBootOption",
	"NtFilterToken"		,
	"NtFilterTokenEx",
	"NtFindAtom"		,
	"NtFlushBuffersFile"	,
	"NtFlushBuffersFileEx",
	"NtFlushInstallUILanguage"	,
	"NtFlushInstructionCache",
	"NtFlushKey"									  	 ,
	"NtFlushProcessWriteBuffers"	,
	"NtFlushVirtualMemory"		,
	"NtFlushWriteBuffer"		,
	"NtFreeUserPhysicalPages"	,
	"NtFreeVirtualMemory"	,
	"NtFreezeRegistry"		,
	"NtFreezeTransactions"	,
	"NtFsControlFile"		,
	"NtGetCachedSigningLevel",
	"NtGetCompleteWnfStateSubscription",
	"NtGetContextThread"		,
	"NtGetCurrentProcessorNumber" 	,
	"NtGetCurrentProcessorNumberEx",
	"NtGetDevicePowerState"		,
	"NtGetMUIRegistryInfo"	,
	"NtGetNextProcess"		,
	"NtGetNextThread"		,
	"NtGetNlsSectionPtr"	,
	"NtGetNotificationResourceManager"	,
	"NtGetPlugPlayEvent"	,
	"NtGetWriteWatch"		,
	"NtImpersonateAnonymousToken"		,
	"NtImpersonateClientOfPort"	,
	"NtImpersonateThread"	,
	"NtInitializeNlsFiles"	,
	"NtInitializeRegistry"		,
	"NtInitiatePowerAction"		,
	"NtIsProcessInJob"	,
	"NtIsSystemResumeAutomatic"	,
	"NtIsUILanguageComitted"	,
	"NtListenPort"		,
	"NtLoadDriver"	,
	"NtLoadKey"	,
	"NtLoadKey2",
	"NtLoadKeyEx"		,
	"NtLockFile"	,
	"NtLockProductActivationKeys"		,
	"NtLockRegistryKey"			,
	"NtLockVirtualMemory"		,
	"NtMakePermanentObject"		,
	"NtMakeTemporaryObject"		,
	"NtMapCMFModule",
	"NtMapUserPhysicalPages"	,
	"NtMapUserPhysicalPagesScatter"	,
	"NtMapViewOfSection"		,
	"NtMapViewOfSectionEx",
	"NtMarshallTransaction",
	"NtModifyBootEntry"			,
	"NtModifyDriverEntry"		,
	"NtNotifyChangeDirectoryFile"	,
	"NtNotifyChangeDirectoryFileEx",
	"NtNotifyChangeKey"				,
	"NtNotifyChangeMultipleKeys"	,
	"NtNotifyChangeSession"			,
	"NtOpenDirectoryObject"		,
	"NtOpenEnlistment"		,
	"NtOpenEvent"			,
	"NtOpenEventPair"		,
	"NtOpenFile"		,
	"NtOpenIoCompletion"	,
	"NtOpenJobObject"	,
	"NtOpenKey"			,
	"NtOpenKeyEx"			,
	"NtOpenKeyTransacted"	,
	"NtOpenKeyTransactedEx"		,
	"NtOpenKeyedEvent"		,
	"NtOpenMutant"					,
	"NtOpenObjectAuditAlarm"	,
	"NtOpenPartition",
	"NtOpenPrivateNamespace"	,
	"NtOpenProcess"			,
	"NtOpenProcessToken	"	,
	"NtOpenProcessTokenEx"		,
	"NtOpenRegistryTransaction",
	"NtOpenResourceManager"	,
	"NtOpenSection"		,
	"NtOpenSemaphore"	,
	"NtOpenSession"			,
	"NtOpenSymbolicLinkObject"	,
	"NtOpenThread"					,
	"NtOpenThreadToken"		,
	"NtOpenThreadTokenEx"	,
	"NtOpenTimer"			,
	"NtOpenTransaction"		,
	"NtOpenTransactionManager"	,
	"NtPlugPlayControl"		,
	"NtPowerInformation"	,
	"NtPrePrepareComplete"	,
	"NtPrePrepareEnlistment"	,
	"NtPrepareComplete"		,
	"NtPrepareEnlistment"		,
	"NtPrivilegeCheck"				,
	"NtPrivilegeObjectAuditAlarm"		,
	"NtPrivilegedServiceAuditAlarm"		,
	"NtPropagationComplete"					,
	"NtPropagationFailed"				,
	"NtProtectVirtualMemory"			,
	"NtPssCaptureVaSpaceBulk",
	"NtPullTransaction",
	"NtPulseEvent"				,
	"NtQueryAttributesFile"			,
	"NtQueryAuxiliaryCounterFrequency",
	"NtQueryBootEntryOrder"		,
	"NtQueryBootOptions"		,
	"NtQueryDebugFilterState"		,
	"NtQueryDefaultLocale"		,
	"NtQueryDefaultUILanguage"		,
	"NtQueryDirectoryFile"		,
	"NtQueryDirectoryFileEx",
	"NtQueryDirectoryObject"		,
	"NtQueryDriverEntryOrder"	,
	"NtQueryEaFile"				,
	"NtQueryEvent"				,
	"NtQueryFullAttributesFile"		,
	"NtQueryInformationAtom"		,
	"NtQueryInformationByName",
	"NtQueryInformationEnlistment"	,
	"NtQueryInformationFile"	,
	"NtQueryInformationJobObject"	,
	"NtQueryInformationPort"	,
	"NtQueryInformationProcess"		,
	"NtQueryInformationResourceManager"	,
	"NtQueryInformationThread"		,
	"NtQueryInformationToken"		,
	"NtQueryInformationTransaction"		,
	"NtQueryInformationTransactionManager"	,
	"NtQueryInformationWorkerFactory",
	"NtQueryInstallUILanguage"	,
	"NtQueryIntervalProfile",
	"NtQueryKey"			,
	"NtQueryLicenseValue"		,
	"NtQueryMultipleValueKey"	,
	"NtQueryMutant"				,
	"NtQueryObject"			,
	"NtQueryOpenSubKeys"		,
	"NtQueryOpenSubKeysEx"		,
	"NtQueryPerformanceCounter"	,
	"NtQueryPortInformationProcess"	,
	"NtQueryQuotaInformationFile"	,
	"NtQuerySection"				,
	"NtQuerySecurityAttributesToken"	,
	"NtQuerySecurityObject"	,
	"NtQuerySecurityPolicy",
	"NtQuerySemaphore"		,
	"NtQuerySymbolicLinkObject"	,
	"NtQuerySystemEnvironmentValue"	,
	"NtQuerySystemEnvironmentValueEx",
	"NtQuerySystemInformation"		,
	"NtQuerySystemInformationEx"	,
					
	"NtQueryTimer"			,
	"NtQueryTimerResolution"	,
	"NtQueryValueKey"			,
	"NtQueryVirtualMemory"		,
	"NtQueryVolumeInformationFile"	,
	"NtQueryWnfStateData",
	"NtQueryWnfStateNameInformation",
	"NtQueueApcThread"		,
	"NtQueueApcThreadEx"	,
	"NtRaiseException"		,
	"NtRaiseHardError"	,
	"NtReadFile"		,
	"NtReadFileScatter"	,
	"NtReadOnlyEnlistment"	,
	"NtReadRequestData"	,
	"NtReadVirtualMemory"	,
	"NtRecoverEnlistment"	,
	"NtRecoverResourceManager"	,
	"NtRecoverTransactionManager"	,
	"NtRegisterProtocolAddressInformation",
	"NtRegisterThreadTerminatePort"	,
	"NtReleaseCMFViewOwnership",
	"NtReleaseKeyedEvent"		,
	"NtReleaseMutant"		,
	"NtReleaseSemaphore"	,
	"NtReleaseWorkerFactoryWorker"	,
	"NtRemoveIoCompletion",
	"NtRemoveIoCompletionEx"	,
	"NtRemoveProcessDebug",
	"NtRenameKey"		,
	"NtRenameTransactionManager",
	"NtReplaceKey"			,
	"NtReplacePartitionUnit"	,
	"NtReplyPort"			,
	"NtReplyWaitReceivePort"	,
	"NtReplyWaitReceivePortEx",
	"NtReplyWaitReplyPort"		,
	"NtRequestDeviceWakeup",
	"NtRequestPort"				,
	"NtRequestWaitReplyPort"	,
	"NtRequestWakeupLatency",
	"NtResetEvent"			,
	"NtResetWriteWatch"	,
	"NtRestoreKey"		,
	"NtResumeProcess"	,
	"NtResumeThread"	,
	"NtRevertContainerImpersonation",
	"NtRollbackComplete"		,
	"NtRollbackEnlistment"		,
	"NtRollbackRegistryTransaction",
	"NtRollbackSavepointTransaction",
	"NtRollbackTransaction"			,
	"NtRollforwardTransactionManager"	,
	"NtSaveKey"			,
	"NtSaveKeyEx"		,
	"NtSaveMergedKeys"	,
	"NtSavepointComplete",
	"NtSavepointTransaction",
	"NtSecureConnectPort"	,
	"NtSerializeBoot"		,
	"NtSetBootEntryOrder"		,
	"NtSetBootOptions",
	"NtSetCachedSigningLevel",
	"NtSetCachedSigningLevel2",
	"NtSetContextThread	"		,
	"NtSetDebugFilterState"		,
	"NtSetDefaultHardErrorPort"	,
	"NtSetDefaultLocale"		,
	"NtSetDefaultUILanguage"	,
	"NtSetDriverEntryOrder"		,
	"NtSetEaFile"				,
	"NtSetEvent"				,
	"NtSetEventBoostPriority"	,
	"NtSetHighEventPair"		,
	"NtSetHighWaitLowEventPair"	,
	"NtSetIRTimer",
	"NtSetInformationDebugObject",
	"NtSetInformationEnlistment",
	"NtSetInformationFile"		,
	"NtSetInformationJobObject"	,
	"NtSetInformationKey"		,
	"NtSetInformationObject"	,
	"NtSetInformationResourceManager",
	"NtSetInformationSymbolicLink",
	"NtSetInformationThread",
	"NtSetInformationToken"		,
	"NtSetInformationTransaction"	,
	"NtSetInformationTransactionManager"	,
	"NtSetInformationVirtualMemory",
	"NtSetInformationWorkerFactory"	,
	"NtSetIntervalProfile"		,
	"NtSetIoCompletion"			,
	"NtSetIoCompletionEx"		,
	"NtSetLdtEntries"		,
	"NtSetLowEventPair"		,
	"NtSetLowWaitHighEventPair"	,
	"NtSetQuotaInformationFile"		,
	"NtSetSystemEnvironmentValue",
	"NtSetSystemEnvironmentValueEx"	,
	"NtSetSystemInformation",
	"NtSetSystemPowerState"		,
	"NtSetSystemTime"		,
	"NtSetThreadExecutionState"		,
	"NtSetTimer"		,
	"NtSetTimer2",
	"NtSetTimerEx"	,
	"NtSetTimerResolution",
	"NtSetUuidSeed"		,
	"NtSetWnfProcessNotificationEvent",
	"NtShutdownSystem"			,
	"NtShutdownWorkerFactory"	,
	"NtSignalAndWaitForSingleObject",
	"NtSinglePhaseReject"	,
	"NtStartProfile"	,
	"NtStartTm",
	"NtStopProfile"		,
	"NtSubscribeWnfStateChange",
	"NtSuspendProcess"		,
	"NtSuspendThread"	,
	"NtSystemDebugControl"	,
	"NtTerminateEnclave",
	"NtTerminateJobObject",
	"NtTerminateProcess",
	"NtTerminateThread"	,
	"NtTestAlert"		,
	"NtThawRegistry",
	"NtTraceControl"	,
	"NtTraceEvent"	,
	"NtTranslateFilePath",
	"NtUmsThreadYield"	,
	"NtUnloadDriver	"	,
	"NtUnloadKey"	,
	"NtUnloadKey2"	,
	"NtUnloadKeyEx"	,
	"NtUnlockFile"	,
	"NtUnlockVirtualMemory"	,
	"NtUnmapViewOfSection"	,
	"NtWaitForDebugEvent"	,
	"NtWaitForKeyedEvent"	,
	"NtWaitForMultipleObjects32",
	"NtWaitForSingleObject"		,
	"NtWaitForWnfNotifications",
	"NtWaitForWorkViaWorkerFactory"	,
	"NtWaitHighEventPair"	,
	"NtWaitLowEventPair	"	,
	"NtWriteFileGather"		,
	"NtWriteRequestData"	,
	"NtWriteVirtualMemory"	,
	"NtYieldExecution"
};
//56th line

static char *win32ksys[] = {
	"NtUserYieldTask",
	"NtUserSetSensorPresence",
	"NtUserGetThreadState",
	"NtUserPeekMessage",
	"NtUserCallOneParam",
	"NtUserGetKeyState",
	"NtUserInvalidateRect",
	"NtUserCallNoParam",
	"NtUserGetMessage",
	"NtUserMessageCall",
	"NtGdiBitBlt",
	"NtGdiGetCharSet",
	"NtUserGetDC",
	"NtGdiSelectBitmap",
	//"NtUserWaitMessage",
	"NtUserTranslateMessage",
	"NtUserGetProp",
	"NtUserPostMessage",
	"NtUserQueryWindow",
	"NtUserTranslateAccelerator",
	"NtGdiFlush",
	"NtUserRedrawWindow",
	"NtUserWindowFromPhysicalPoint",
	"NtUserCallMsgFilter",
	"NtUserValidateTimerCallback",
	"NtUserBeginPaint",
	"NtUserSetTimer",
	"NtUserEndPaint",
	"NtUserSetCursor",
	"NtUserKillTimer",
	"NtUserBuildHwndList",
	"NtUserSelectPalette",
	"NtUserCallNextHookEx",
	"NtUserHideCaret",
	"NtGdiIntersectClipRect",
	"NtUserCallHwndLock",
	"NtUserGetProcessWindowStation",
	"NtGdiDeleteObjectApp",
	"NtUserSetWindowPos",
	"NtUserShowCaret",
	"NtUserEndDeferWindowPosEx",
	"NtUserCallHwndParamLock",
	"NtUserVkKeyScanEx",
	"NtGdiSetDIBitsToDeviceInternal",
	"NtUserCallTwoParam",
	"NtGdiGetRandomRgn",
	"NtUserCopyAcceleratorTable",
	"NtUserNotifyWinEvent",
	"NtGdiExtSelectClipRgn",
	"NtUserIsClipboardFormatAvailable",
	"NtUserSetScrollInfo",
	"NtGdiStretchBlt",
	"NtUserCreateCaret",
	"NtGdiRectVisible",
	"NtGdiCombineRgn",
	"NtGdiGetDCObject",
	"NtUserDispatchMessage",
	"NtUserRegisterWindowMessage",
	"NtGdiExtTextOutW",
	"NtGdiSelectFont",
	"NtGdiRestoreDC",
	"NtGdiSaveDC",
	"NtUserGetForegroundWindow",
	"NtUserShowScrollBar",
	"NtUserFindExistingCursorIcon",
	"NtGdiGetDCDword",
	"NtGdiGetRegionData",
	"NtGdiLineTo",
	"NtUserSystemParametersInfo",
	"NtGdiGetAppClipBox",
	"NtUserGetAsyncKeyState",
	"NtUserGetCPD",
	"NtUserRemoveProp",
	"NtGdiDoPalette",
	"NtGdiPolyPolyDraw",
	"NtUserSetCapture",
	"NtUserEnumDisplayMonitors",
	"NtGdiCreateCompatibleBitmap",
	"NtUserSetProp",
	"NtGdiGetTextCharsetInfo",
	"NtUserSBGetParms",
	"NtUserGetIconInfo",
	"NtUserExcludeUpdateRgn",
	"NtUserSetFocus",
	"NtGdiExtGetObjectW",
	"NtUserGetUpdateRect",
	"NtGdiCreateCompatibleDC",
	"NtUserGetClipboardSequenceNumber",
	"NtGdiCreatePen",
	"NtUserShowWindow",
	"NtUserGetKeyboardLayoutList",
	"NtGdiPatBlt",
	"NtUserMapVirtualKeyEx",
	"NtUserSetWindowLong",
	"NtGdiHfontCreate",
	"NtUserMoveWindow",
	"NtUserPostThreadMessage",
	"NtUserDrawIconEx",
	"NtUserGetSystemMenu",
	"NtGdiDrawStream",
	"NtUserInternalGetWindowText",
	"NtUserGetWindowDC",
	"NtGdiDvpGetVideoPortBandwidth",
	"NtGdiInvertRgn",
	"NtGdiGetRgnBox",
	"NtGdiGetAndSetDCDword",
	"NtGdiMaskBlt",
	"NtGdiGetWidthTable",
	"NtUserScrollDC",
	"NtUserGetObjectInformation",
	"NtGdiCreateBitmap",
	"NtUserFindWindowEx",
	"NtGdiPolyPatBlt",
	"NtUserUnhookWindowsHookEx",
	"NtGdiGetNearestColor",
	"NtGdiTransformPoints",
	"NtGdiGetDCPoint",
	"NtGdiCreateDIBBrush",
	"NtGdiGetTextMetricsW",
	"NtUserCreateWindowEx",
	"NtUserSetParent",
	"NtUserGetKeyboardState",
	"NtUserToUnicodeEx",
	"NtUserGetControlBrush",
	"NtUserGetClassName",
	"NtGdiAlphaBlend",
	"NtGdiDdCreateMoComp",
	"NtGdiOffsetRgn",
	"NtUserDefSetText",
	"NtGdiGetTextFaceW",
	"NtGdiStretchDIBitsInternal",
	"NtUserSendInput",
	"NtUserGetThreadDesktop",
	"NtGdiCreateRectRgn",
	"NtGdiGetDIBitsInternal",
	"NtUserGetUpdateRgn",
	"NtGdiDeleteClientObj",
	"NtUserGetIconSize",
	"NtUserFillWindow",
	"NtGdiExtCreateRegion",
	"NtGdiComputeXformCoefficients",
	"NtUserSetWindowsHookEx",
	"NtUserNotifyProcessCreate",
	"NtGdiUnrealizeObject",
	"NtUserGetTitleBarInfo",
	"NtGdiRectangle",
	"NtUserSetThreadDesktop",
	"NtUserGetDCEx",
	"NtUserGetScrollBarInfo",
	"NtGdiGetTextExtent",
	"NtUserSetWindowFNID",
	"NtGdiSetLayout",
	"NtUserCalcMenuBar",
	"NtUserThunkedMenuItemInfo",
	"NtGdiExcludeClipRect",
	"NtGdiCreateDIBSection",
	"NtGdiGetDCforBitmap",
	"NtUserDestroyCursor",
	"NtUserDestroyWindow",
	"NtUserCallHwndParam",
	"NtGdiCreateDIBitmapInternal",
	"NtUserOpenWindowStation",
	"NtGdiDdUpdateOverlay",
	"NtGdiDdGetInternalMoCompInfo",
	"NtGdiDdGetMoCompBuffInfo",
	"NtUserSetCursorIconData",
	"NtGdiDvpCreateVideoPort",
	"NtUserCloseDesktop",
	"NtUserOpenDesktop",
	"NtUserSetProcessWindowStation",
	"NtUserGetAtomName",
	"NtGdiDvpAcquireNotification",
	"NtGdiExtCreatePen",
	"NtGdiCreatePaletteInternal",
	"NtGdiSetBrushOrg",
	"NtUserBuildNameList",
	"NtGdiSetPixel",
	"NtUserRegisterClassExWOW",
	"NtGdiCreatePatternBrushInternal",
	"NtUserGetAncestor",
	"NtGdiGetOutlineTextMetricsInternalW",
	"NtGdiSetBitmapBits",
	"NtUserCloseWindowStation",
	"NtUserGetDoubleClickTime",
	"NtUserEnableScrollBar",
	"NtGdiCreateSolidBrush",
	"NtUserGetClassInfoEx",
	"NtGdiCreateClientObj",
	"NtUserUnregisterClass",
	"NtUserDeleteMenu",
	"NtGdiRectInRegion",
	"NtUserScrollWindowEx",
	"NtGdiGetPixel",
	"NtUserSetClassLong",
	"NtUserGetMenuBarInfo",
	"NtGdiDdUnlockD3D",
	"NtGdiDdGetScanLine",
	"NtGdiGetNearestPaletteIndex",
	"NtGdiDdCreateD3DBuffer",
	"NtGdiDdResetVisrgn",
	"NtGdiGetCharWidthW",
	"NtUserInvalidateRgn",
	"NtUserGetClipboardOwner",
	"NtUserSetWindowRgn",
	"NtUserBitBltSysBmp",
	"NtGdiGetCharWidthInfo",
	"NtUserValidateRect",
	"NtUserCloseClipboard",
	"NtUserOpenClipboard",
	"NtGdiGetStockObject",
	"NtUserSetClipboardData",
	"NtUserEnableMenuItem",
	"NtUserAlterWindowStyle",
	"NtGdiFillRgn",
	"NtUserGetWindowPlacement",
	"NtGdiModifyWorldTransform",
	"NtGdiGetFontData",
	"NtUserGetOpenClipboardWindow",
	"NtUserSetThreadState",
	"NtGdiOpenDCW",
	"NtUserTrackMouseEvent",
	"NtGdiGetTransform",
	"NtUserDestroyMenu",
	"NtGdiGetBitmapBits",
	"NtUserConsoleControl",
	"NtUserSetActiveWindow",
	"NtUserSetInformationThread",
	"NtUserSetWindowPlacement",
	"NtUserGetControlColor",
	"NtGdiSetMetaRgn",
	"NtGdiSetMiterLimit",
	"NtGdiSetVirtualResolution",
	"NtGdiGetRasterizerCaps",
	"NtUserSetWindowWord",
	"NtUserGetClipboardFormatName",
	"NtUserRealInternalGetMessage",
	"NtUserCreateLocalMemHandle",
	"NtUserAttachThreadInput",
	"NtGdiCreateHalftonePalette",
	"NtUserPaintMenuBar",
	"NtUserSetKeyboardState",
	"NtGdiCombineTransform",
	"NtUserCreateAcceleratorTable",
	"NtUserGetCursorFrameInfo",
	"NtUserGetAltTabInfo",
	"NtUserGetCaretBlinkTime",
	"NtGdiQueryFontAssocInfo",
	"NtUserProcessConnect",
	"NtUserEnumDisplayDevices",
	"NtUserEmptyClipboard",
	"NtUserGetClipboardData",
	"NtUserRemoveMenu",
	"NtGdiSetBoundsRect",
	"NtGdiGetBitmapDimension",
	"NtUserConvertMemHandle",
	"NtUserDestroyAcceleratorTable",
	"NtUserGetGUIThreadInfo",
	"NtGdiCloseFigure",
	"NtUserSetWindowsHookAW",
	"NtUserSetMenuDefaultItem",
	"NtUserCheckMenuItem",
	"NtUserSetWinEventHook",
	"NtUserUnhookWinEvent",
	"NtUserLockWindowUpdate",
	"NtUserSetSystemMenu",
	"NtUserThunkedMenuInfo",
	"NtGdiBeginPath",
	"NtGdiEndPath",
	"NtGdiFillPath",
	"NtUserCallHwnd",
	"NtUserDdeInitialize",
	"NtUserModifyUserStartupInfoFlags",
	"NtUserCountClipboardFormats",
	"NtGdiAddFontMemResourceEx",
	"NtGdiEqualRgn",
	"NtGdiGetSystemPaletteUse",
	"NtGdiRemoveFontMemResourceEx",
	"NtUserEnumDisplaySettings",
	"NtUserPaintDesktop",
	"NtGdiExtEscape",
	"NtGdiSetBitmapDimension",
	"NtGdiSetFontEnumeration",
	"NtUserChangeClipboardChain",
	"NtUserSetClipboardViewer",
	"NtUserShowWindowAsync",
	"NtGdiCreateColorSpace",
	"NtGdiDeleteColorSpace",
	"NtUserActivateKeyboardLayout",
	"NtBindCompositionSurface",
	"NtCompositionInputThread",
	"NtCreateCompositionInputSink",
	"NtCreateCompositionSurfaceHandle",
	"NtDCompositionAddCrossDeviceVisualChild",
	"NtDCompositionAddVisualChild",
	"NtDCompositionBeginFrame",
	"NtDCompositionCommitChannel",
	"NtDCompositionConfirmFrame",
	"NtDCompositionGetChannels",
	"NtDCompositionCreateAndBindSharedSection",
	"NtDCompositionCreateChannel",
	"NtDCompositionCreateConnection",
	"NtDCompositionCreateDwmChannel",
	"NtDCompositionCreateResource",
	"NtDCompositionCurrentBatchId",
	"NtDCompositionDestroyChannel",
	"NtDCompositionDestroyConnection",
	"NtDCompositionDiscardFrame",
	"NtDCompositionDuplicateHandleToProcess",
	"NtDCompositionDwmSyncFlush",
	"NtDCompositionConnectPipe",
	"NtDCompositionGetConnectionBatch",
	"NtDCompositionGetDeletedResources",
	"NtDCompositionGetFrameLegacyTokens",
	"NtDCompositionGetFrameStatistics",
	"NtDCompositionGetFrameSurfaceUpdates",
	"NtDCompositionOpenSharedResource",
	"NtDCompositionOpenSharedResourceHandle",
	"NtDCompositionReferenceSharedResourceOnDwmChannel",
	"NtDCompositionRegisterThumbnailVisual",
	"NtDCompositionReleaseAllResources",
	"NtDCompositionReleaseResource",
	"NtDCompositionRemoveCrossDeviceVisualChild",
	"NtDCompositionRemoveVisualChild",
	"NtDCompositionReplaceVisualChildren",
	"NtDCompositionRetireFrame",
	"NtDCompositionSetChannelCommitCompletionEvent",
	"NtDCompositionSetDebugCounter",
	"NtDCompositionSetResourceAnimationProperty",
	"NtDCompositionSetResourceBufferProperty",
	"NtDCompositionSetResourceDeletedNotificationTag",
	"NtDCompositionSetResourceFloatProperty",
	"NtDCompositionSetResourceHandleProperty",
	"NtDCompositionSetResourceIntegerProperty",
	"NtDCompositionSetResourceReferenceArrayProperty",
	"NtDCompositionSetResourceReferenceProperty",
	"NtDCompositionSignalGpuFence",
	"NtDCompositionSubmitDWMBatch",
	"NtDCompositionSynchronize",
	"NtDCompositionTelemetryAnimationScenarioBegin",
	"NtDCompositionTelemetryAnimationScenarioReference",
	"NtDCompositionTelemetryAnimationScenarioUnreference",
	"NtDCompositionTelemetrySetApplicationId",
	"NtDCompositionTelemetryTouchInteractionBegin",
	"NtDCompositionTelemetryTouchInteractionEnd",
	"NtDCompositionTelemetryTouchInteractionUpdate",
	"NtDCompositionWaitForChannel",
	"NtDuplicateCompositionInputSink",
	"NtGdiAbortDoc",
	"NtGdiAbortPath",
	"NtGdiAddEmbFontToDC",
	"NtGdiAddFontResourceW",
	"NtGdiAddRemoteFontToDC",
	"NtGdiAddRemoteMMInstanceToDC",
	"NtGdiAngleArc",
	"NtGdiAnyLinkedFonts",
	"NtGdiArcInternal",
	"NtGdiBRUSHOBJ_DeleteRbrush",
	"NtGdiBRUSHOBJ_hGetColorTransform",
	"NtGdiBRUSHOBJ_pvAllocRbrush",
	"NtGdiBRUSHOBJ_pvGetRbrush",
	"NtGdiBRUSHOBJ_ulGetBrushColor",
	"NtGdiBeginGdiRendering",
	"NtGdiCLIPOBJ_bEnum",
	"NtGdiCLIPOBJ_cEnumStart",
	"NtGdiCLIPOBJ_ppoGetPath",
	"NtGdiCancelDC",
	"NtGdiChangeGhostFont",
	"NtGdiCheckBitmapBits",
	"NtGdiClearBitmapAttributes",
	"NtGdiUnloadPrinterDriver",
	"NtGdiColorCorrectPalette",
	"NtGdiConfigureOPMProtectedOutput",
	"NtGdiConvertMetafileRect",
	"NtGdiCreateBitmapFromDxSurface",
	"NtGdiCreateBitmapFromDxSurface2",
	"NtGdiCreateColorTransform",
	"NtGdiCreateEllipticRgn",
	"NtGdiCreateHatchBrushInternal",
	"NtGdiCreateMetafileDC",
	"NtGdiCreateOPMProtectedOutputs",
	"NtGdiCreateRoundRectRgn",
	"NtGdiCreateServerMetaFile",
	"NtGdiCreateSessionMappedDIBSection",
	"NtGdiDdDeleteDirectDrawObject",
	"NtGdiDvpUpdateVideoPort",
	"NtGdiDdUnlock",
	"NtGdiDdCanCreateSurface",
	"NtGdiDDCCIGetCapabilitiesString",
	"NtGdiDDCCIGetCapabilitiesStringLength",
	"NtGdiDDCCIGetTimingReport",
	"NtGdiDDCCIGetVCPFeature",
	"NtGdiDDCCISaveCurrentSettings",
	"NtGdiDDCCISetVCPFeature",
	"NtGdiDvpGetVideoPortOutputFormats",
	"NtGdiDdGetFlipStatus",
	"NtGdiDvpGetVideoPortField",
	"NtGdiDdSetGammaRamp",
	"NtGdiD3dContextCreate",
	"NtGdiDdDestroySurface",
	"NtGdiDvpReleaseNotification",
	"NtGdiDdAlphaBlt",
	"NtGdiDdCreateFullscreenSprite",
	"NtGdiDdGetAvailDriverMemory",
	"NtGdiDdDDIAcquireKeyedMutex",
	"NtGdiDdDDIAcquireKeyedMutex2",
	"NtGdiDdDDICacheHybridQueryValue",
	"NtGdiDdDDICheckExclusiveOwnership",
	"NtGdiDdDDICheckMonitorPowerState",
	"NtGdiDdDDICheckMultiPlaneOverlaySupport",
	"NtGdiDdDDICheckOcclusion",
	"NtGdiDdDDICheckSharedResourceAccess",
	"NtGdiDdDDICheckVidPnExclusiveOwnership",
	"NtGdiDdDDICloseAdapter",
	"NtGdiDdDDIConfigureSharedResource",
	"NtGdiDdDDICreateAllocation",
	"NtGdiDdDDICreateContext",
	"NtGdiDdDDICreateDCFromMemory",
	"NtGdiDdDDICreateDevice",
	"NtGdiDdDDICreateKeyedMutex",
	"NtGdiDdDDICreateKeyedMutex2",
	"NtGdiDdDDICreateOutputDupl",
	"NtGdiDdDDICreateOverlay",
	"NtGdiDdDDICreateSynchronizationObject",
	"NtGdiDdDDIDestroyAllocation",
	"NtGdiDdDDIDestroyContext",
	"NtGdiDdDDIDestroyDCFromMemory",
	"NtGdiDdDDIDestroyDevice",
	"NtGdiDdDDIDestroyKeyedMutex",
	"NtGdiDdDDIDestroyOutputDupl",
	"NtGdiDdDDIDestroyOverlay",
	"NtGdiDdDDIDestroySynchronizationObject",
	"NtGdiDdDDIEnumAdapters",
	"NtGdiDdDDIEscape",
	"NtGdiDdDDIFlipOverlay",
	"NtGdiDdDDIGetCachedHybridQueryValue",
	"NtGdiDdDDIGetContextInProcessSchedulingPriority",
	"NtGdiDdDDIGetContextSchedulingPriority",
	"NtGdiDdDDIGetDeviceState",
	"NtGdiDdDDIGetDisplayModeList",
	"NtGdiDdDDIGetMultisampleMethodList",
	"NtGdiDdDDIGetOverlayState",
	"NtGdiDdDDIGetPresentHistory",
	"NtGdiDdDDIGetPresentQueueEvent",
	"NtGdiDdDDIGetProcessSchedulingPriorityClass",
	"NtGdiDdDDIGetRuntimeData",
	"NtGdiDdDDIGetScanLine",
	"NtGdiDdDDIGetSharedPrimaryHandle",
	"NtGdiDdDDIGetSharedResourceAdapterLuid",
	"NtGdiDdDDIInvalidateActiveVidPn",
	"NtGdiDdDDILock",
	"NtGdiDdDDINetDispGetNextChunkInfo",
	"NtGdiDdDDINetDispQueryMiracastDisplayDeviceStatus",
	"NtGdiDdDDINetDispQueryMiracastDisplayDeviceSupport",
	"NtGdiDdDDINetDispStartMiracastDisplayDevice",
	"NtGdiDdDDINetDispStopMiracastDisplayDevice",
	"NtGdiDdDDIOfferAllocations",
	"NtGdiDdDDIOpenAdapterFromDeviceName",
	"NtGdiDdDDIOpenAdapterFromHdc",
	"NtGdiDdDDIOpenAdapterFromLuid",
	"NtGdiDdDDIOpenKeyedMutex",
	"NtGdiDdDDIOpenKeyedMutex2",
	"NtGdiDdDDIOpenNtHandleFromName",
	"NtGdiDdDDIOpenResource",
	"NtGdiDdDDIOpenResourceFromNtHandle",
	"NtGdiDdDDIOpenSyncObjectFromNtHandle",
	"NtGdiDdDDIOpenSynchronizationObject",
	"NtGdiDdDDIOutputDuplGetFrameInfo",
	"NtGdiDdDDIOutputDuplGetMetaData",
	"NtGdiDdDDIOutputDuplGetPointerShapeData",
	"NtGdiDdDDIOutputDuplPresent",
	"NtGdiDdDDIOutputDuplReleaseFrame",
	"NtGdiDdDDIPinDirectFlipResources",
	"NtGdiDdDDIPollDisplayChildren",
	"NtGdiDdDDIPresent",
	"NtGdiDdDDIPresentMultiPlaneOverlay",
	"NtGdiDdDDIQueryAdapterInfo",
	"NtGdiDdDDIQueryAllocationResidency",
	"NtGdiDdDDIQueryRemoteVidPnSourceFromGdiDisplayName",
	"NtGdiDdDDIQueryResourceInfo",
	"NtGdiDdDDIQueryResourceInfoFromNtHandle",
	"NtGdiDdDDIQueryStatistics",
	"NtGdiDdDDIReclaimAllocations",
	"NtGdiDdDDIReleaseKeyedMutex",
	"NtGdiDdDDIReleaseKeyedMutex2",
	"NtGdiDdDDIReleaseProcessVidPnSourceOwners",
	"NtGdiDdDDIRender",
	"NtGdiDdDDISetAllocationPriority",
	"NtGdiDdDDISetContextInProcessSchedulingPriority",
	"NtGdiDdDDISetContextSchedulingPriority",
	"NtGdiDdDDISetDisplayMode",
	"NtGdiDdDDISetDisplayPrivateDriverFormat",
	"NtGdiDdDDISetGammaRamp",
	"NtGdiDdDDISetProcessSchedulingPriorityClass",
	"NtGdiDdDDISetQueuedLimit",
	"NtGdiDdDDISetStereoEnabled",
	"NtGdiDdDDISetVidPnSourceOwner",
	"NtGdiDdDDISetVidPnSourceOwner1",
	"NtGdiDdDDIShareObjects",
	"NtGdiDdDDISharedPrimaryLockNotification",
	"NtGdiDdDDISharedPrimaryUnLockNotification",
	"NtGdiDdDDISignalSynchronizationObject",
	"NtGdiDdDDIUnlock",
	"NtGdiDdDDIUnpinDirectFlipResources",
	"NtGdiDdDDIUpdateOverlay",
	"NtGdiDdDDIWaitForIdle",
	"NtGdiDdDDIWaitForSynchronizationObject",
	"NtGdiDdDDIWaitForVerticalBlankEvent",
	"NtGdiDdDDIWaitForVerticalBlankEvent2",
	"NtGdiDvpCanCreateVideoPort",
	"NtGdiDdCreateSurfaceEx",
	"NtGdiDdDestroyFullscreenSprite",
	"NtGdiDdSetExclusiveMode",
	"NtGdiDdEndMoCompFrame",
	"NtGdiDdLockD3D",
	"NtGdiDdBlt",
	"NtGdiDdDestroyD3DBuffer",
	"NtGdiD3dValidateTextureStageState",
	"NtGdiDdDestroyMoComp",
	"NtGdiDvpGetVideoPortFlipStatus",
	"NtGdiDdSetColorKey",
	"NtGdiDvpGetVideoPortConnectInfo",
	"NtGdiDdWaitForVerticalBlank",
	"NtGdiDdCreateSurfaceObject",
	"NtGdiDdReenableDirectDrawObject",
	"NtGdiDvpGetVideoSignalStatus",
	"NtGdiDvpFlipVideoPort",
	"NtGdiD3dContextDestroy",
	"NtGdiDvpColorControl",
	"NtGdiDdNotifyFullscreenSpriteUpdate",
	"NtGdiDdGetDC",
	"NtGdiDdDeleteSurfaceObject",
	"NtGdiDdQueryVisRgnUniqueness",
	"NtGdiDdReleaseDC",
	"NtGdiDdColorControl",
	"NtGdiDvpDestroyVideoPort",
	"NtGdiDdAttachSurface",
	"NtGdiDdGetDxHandle",
	"NtGdiDdQueryDirectDrawObject",
	"NtGdiDdSetOverlayPosition",
	"NtGdiDdUnattachSurface",
	"NtGdiDdGetBltStatus",
	"NtGdiDdRenderMoComp",
	"NtGdiDdGetMoCompGuids",
	"NtGdiDeleteColorTransform",
	"NtGdiDescribePixelFormat",
	"NtGdiDestroyOPMProtectedOutput",
	"UnknownSyscall",
	"NtGdiDoBanding",
	"NtGdiDrawEscape",
	"NtGdiDdCanCreateD3DBuffer",
	"NtGdiDvpWaitForVideoPortSync",
	"NtGdiD3dContextDestroyAll",
	"NtGdiDdGetDriverInfo",
	"NtGdiDdQueryMoCompStatus",
	"NtGdiDvpGetVideoPortLine",
	"NtGdiDvpGetVideoPortInputFormats",
	"NtGdiDdGetDriverState",
	"NtGdiDdCreateSurface",
	"NtGdiD3dDrawPrimitives2",
	"NtGdiDdFlipToGDISurface",
	"NtGdiDdBeginMoCompFrame",
	"NtGdiDdCreateDirectDrawObject",
	"NtGdiDdAddAttachedSurface",
	"NtGdiDdGetMoCompFormats",
	"NtGdiDdLock",
	"NtGdiDdFlip",
	"NtGdiDwmCreatedBitmapRemotingOutput",
	"NtGdiDxgGenericThunk",
	"NtGdiEllipse",
	"NtGdiEnableEudc",
	"NtGdiEndDoc",
	"NtGdiEndGdiRendering",
	"NtGdiEndPage",
	"NtGdiEngAlphaBlend",
	"NtGdiEngAssociateSurface",
	"NtGdiEngBitBlt",
	"NtGdiEngCheckAbort",
	"NtGdiEngComputeGlyphSet",
	"NtGdiEngCopyBits",
	"NtGdiEngCreateBitmap",
	"NtGdiEngCreateClip",
	"NtGdiEngCreateDeviceBitmap",
	"NtGdiEngCreateDeviceSurface",
	"NtGdiEngCreatePalette",
	"NtGdiEngDeleteClip",
	"NtGdiEngDeletePalette",
	"NtGdiEngDeletePath",
	"NtGdiEngDeleteSurface",
	"NtGdiEngEraseSurface",
	"NtGdiEngFillPath",
	"NtGdiEngGradientFill",
	"NtGdiEngLineTo",
	"NtGdiEngLockSurface",
	"NtGdiEngMarkBandingSurface",
	"NtGdiEngPaint",
	"NtGdiEngPlgBlt",
	"NtGdiEngStretchBlt",
	"NtGdiEngStretchBltROP",
	"NtGdiEngStrokeAndFillPath",
	"NtGdiEngStrokePath",
	"NtGdiEngTextOut",
	"NtGdiEngTransparentBlt",
	"NtGdiEngUnlockSurface",
	"NtGdiEnumFonts",
	"NtGdiEnumObjects",
	"NtGdiEudcLoadUnloadLink",
	"NtGdiExtFloodFill",
	"NtGdiFONTOBJ_cGetAllGlyphHandles",
	"NtGdiFONTOBJ_cGetGlyphs",
	"NtGdiFONTOBJ_pQueryGlyphAttrs",
	"NtGdiFONTOBJ_pfdg",
	"NtGdiFONTOBJ_pifi",
	"NtGdiFONTOBJ_pvTrueTypeFontFile",
	"NtGdiFONTOBJ_pxoGetXform",
	"NtGdiFONTOBJ_vGetInfo",
	"NtGdiFlattenPath",
	"NtGdiFontIsLinked",
	"NtGdiForceUFIMapping",
	"NtGdiFrameRgn",
	"NtGdiFullscreenControl",
	"NtGdiGetBoundsRect",
	"NtGdiGetCOPPCompatibleOPMInformation",
	"NtGdiGetCertificate",
	"NtGdiGetCertificateSize",
	"NtGdiGetCharABCWidthsW",
	"NtGdiGetCharacterPlacementW",
	"NtGdiGetColorAdjustment",
	"NtGdiGetColorSpaceforBitmap",
	"NtGdiGetCurrentDpiInfo",
	"NtGdiGetDeviceCaps",
	"NtGdiGetDeviceCapsAll",
	"NtGdiGetDeviceGammaRamp",
	"NtGdiGetDeviceWidth",
	"NtGdiGetDhpdev",
	"NtGdiGetETM",
	"NtGdiGetEmbUFI",
	"NtGdiGetEmbedFonts",
	"NtGdiGetEudcTimeStampEx",
	"NtGdiGetFontFileData",
	"NtGdiGetFontFileInfo",
	"NtGdiGetFontResourceInfoInternalW",
	"NtGdiGetFontUnicodeRanges",
	"NtGdiGetGlyphIndicesW",
	"NtGdiGetGlyphIndicesWInternal",
	"NtGdiGetGlyphOutline",
	"NtGdiGetKerningPairs",
	"NtGdiGetLinkedUFIs",
	"NtGdiGetMiterLimit",
	"NtGdiGetMonitorID",
	"NtGdiGetNumberOfPhysicalMonitors",
	"NtGdiGetOPMInformation",
	"NtGdiGetOPMRandomNumber",
	"NtGdiGetObjectBitmapHandle",
	"NtGdiGetPath",
	"NtGdiGetPerBandInfo",
	"NtGdiGetPhysicalMonitorDescription",
	"NtGdiGetPhysicalMonitors",
	"NtGdiGetRealizationInfo",
	"NtGdiGetServerMetaFileBits",
	"NtGdiSetBrushAttributes",
	"NtGdiGetStats",
	"NtGdiGetStringBitmapW",
	"NtGdiGetSuggestedOPMProtectedOutputArraySize",
	"NtGdiGetTextExtentExW",
	"NtGdiGetUFI",
	"NtGdiGetUFIPathname",
	"NtGdiGradientFill",
	"NtGdiHLSurfGetInformation",
	"NtGdiHLSurfSetInformation",
	"NtGdiHT_Get8BPPFormatPalette",
	"NtGdiHT_Get8BPPMaskPalette",
	"NtGdiIcmBrushInfo",
	"NtGdiUnmapMemFont",
	"NtGdiInitSpool",
	"NtGdiMakeFontDir",
	"NtGdiMakeInfoDC",
	"NtGdiMakeObjectUnXferable",
	"NtGdiMakeObjectXferable",
	"NtGdiMirrorWindowOrg",
	"NtGdiMonoBitmap",
	"NtGdiMoveTo",
	"NtGdiOffsetClipRgn",
	"NtGdiPATHOBJ_bEnum",
	"NtGdiPATHOBJ_bEnumClipLines",
	"NtGdiPATHOBJ_vEnumStart",
	"NtGdiPATHOBJ_vEnumStartClipLines",
	"NtGdiPATHOBJ_vGetBounds",
	"NtGdiPathToRegion",
	"NtGdiPlgBlt",
	"NtGdiPolyDraw",
	"NtGdiPolyTextOutW",
	"NtGdiPtInRegion",
	"NtGdiPtVisible",
	"NtGdiQueryFonts",
	"NtGdiRemoveFontResourceW",
	"NtGdiRemoveMergeFont",
	"NtGdiResetDC",
	"NtGdiResizePalette",
	"NtGdiRoundRect",
	"NtGdiSTROBJ_bEnum",
	"NtGdiSTROBJ_bEnumPositionsOnly",
	"NtGdiSTROBJ_bGetAdvanceWidths",
	"NtGdiSTROBJ_dwGetCodePage",
	"NtGdiSTROBJ_vEnumStart",
	"NtGdiScaleViewportExtEx",
	"NtGdiScaleWindowExtEx",
	"NtGdiSelectBrush",
	"NtGdiSelectClipPath",
	"NtGdiSelectPen",
	"NtGdiSetBitmapAttributes",
	"NtGdiGetSpoolMessage",
	"NtGdiSetColorAdjustment",
	"NtGdiSetColorSpace",
	"NtGdiSetDeviceGammaRamp",
	"NtGdiSetFontXform",
	"NtGdiSetIcmMode",
	"NtGdiSetLinkedUFIs",
	"NtGdiSetMagicColors",
	"NtGdiSetOPMSigningKeyAndSequenceNumbers",
	"NtGdiSetPUMPDOBJ",
	"NtGdiSetPixelFormat",
	"NtGdiSetRectRgn",
	"NtGdiSetSizeDevice",
	"NtGdiSetSystemPaletteUse",
	"NtGdiSetTextJustification",
	"NtGdiSetUMPDSandboxState",
	"NtGdiStartDoc",
	"NtGdiStartPage",
	"NtGdiStrokeAndFillPath",
	"NtGdiStrokePath",
	"NtGdiSwapBuffers",
	"NtGdiTransparentBlt",
	"NtGdiUMPDEngFreeUserMem",
	"NtGdiClearBrushAttributes",
	"NtUserUpdateWindowTransform",
	"NtGdiUpdateColors",
	"NtGdiUpdateTransform",
	"NtGdiWidenPath",
	"NtGdiXFORMOBJ_bApplyXform",
	"NtGdiXFORMOBJ_iGetXform",
	"NtGdiXLATEOBJ_cGetPalette",
	"NtGdiXLATEOBJ_hGetColorTransform",
	"NtGdiXLATEOBJ_iXlate",
	"NtNotifyPresentToCompositionSurface",
	"NtOpenCompositionSurfaceDirtyRegion",
	"NtOpenCompositionSurfaceSectionInfo",
	"NtOpenCompositionSurfaceSwapChainHandleInfo",
	"NtQueryCompositionInputSink",
	"NtQueryCompositionInputSinkLuid",
	"NtQueryCompositionSurfaceBinding",
	"NtQueryCompositionSurfaceRenderingRealization",
	"NtQueryCompositionSurfaceStatistics",
	"NtSetCompositionSurfaceBufferCompositionMode",
	"NtSetCompositionSurfaceIndependentFlipInfo",
	"NtSetCompositionSurfaceOutOfFrameDirectFlipNotification",
	"NtSetCompositionSurfaceStatistics",
	"NtTokenManagerCreateCompositionTokenHandle",
	"NtTokenManagerDeleteOutstandingDirectFlipTokens",
	"NtTokenManagerGetOutOfFrameDirectFlipSurfaceUpdates",
	"NtTokenManagerOpenEvent",
	"NtTokenManagerOpenSection",
	"NtTokenManagerThread",
	"NtUnBindCompositionSurface",
	"NtUpdateInputSinkTransforms",
	"NtUserAcquireIAMKey",
	"NtUserAddClipboardFormatListener",
	"NtUserAssociateInputContext",
	"NtUserAutoPromoteMouseInPointer",
	"NtUserAutoRotateScreen",
	"NtUserBlockInput",
	"NtUserBuildHimcList",
	"NtUserBuildPropList",
	"NtUserCalculatePopupWindowPosition",
	"NtUserCallHwndOpt",
	"NtUserCanBrokerForceForeground",
	"NtUserChangeDisplaySettings",
	"NtUserChangeWindowMessageFilterEx",
	"NtUserCheckAccessForIntegrityLevel",
	"NtUserCheckProcessForClipboardAccess",
	"NtUserCheckProcessSession",
	"NtUserCheckWindowThreadDesktop",
	"NtUserChildWindowFromPointEx",
	"NtUserClearForeground",
	"NtUserClipCursor",
	"NtUserCompositionInputSinkLuidFromPoint",
	"NtUserCreateDCompositionHwndTarget",
	"NtUserCreateDesktopEx",
	"NtUserCreateInputContext",
	"NtUserCreateWindowStation",
	"NtUserCtxDisplayIOCtl",
	"NtUserDeferWindowPosAndBand",
	"NtUserDelegateCapturePointers",
	"NtUserDelegateInput",
	"NtUserDestroyDCompositionHwndTarget",
	"NtUserDestroyInputContext",
	"NtUserDisableImmersiveOwner",
	"NtUserDisableProcessWindowFiltering",
	"NtUserDisableThreadIme",
	"NtUserDiscardPointerFrameMessages",
	"NtUserDisplayConfigGetDeviceInfo",
	"NtUserDisplayConfigSetDeviceInfo",
	"NtUserDoSoundConnect",
	"NtUserDoSoundDisconnect",
	"NtUserDragDetect",
	"NtUserDragObject",
	"NtUserDrawAnimatedRects",
	"NtUserDrawCaption",
	"NtUserDrawCaptionTemp",
	"NtUserDrawMenuBarTemp",
	"NtUserDwmGetRemoteSessionOcclusionEvent",
	"NtUserDwmGetRemoteSessionOcclusionState",
	"NtUserDwmStartRedirection",
	"NtUserDwmStopRedirection",
	"NtUserDwmValidateWindow",
	"NtUserEnableIAMAccess",
	"NtUserEnableMouseInPointer",
	"NtUserEnableMouseInputForCursorSuppression",
	"NtUserEnableTouchPad",
	"NtUserEndMenu",
	"NtUserEvent",
	"NtUserFlashWindowEx",
	"NtUserFrostCrashedWindow",
	"NtUserGetAppImeLevel",
	"NtUserGetAutoRotationState",
	"NtUserGetCIMSSM",
	"NtUserGetCaretPos",
	"NtUserGetClipCursor",
	"NtUserGetClipboardAccessToken",
	"NtUserGetClipboardViewer",
	"NtUserGetComboBoxInfo",
	"NtUserGetCurrentInputMessageSource",
	"NtUserGetCursorDims",
	"NtUserGetCursorInfo",
	"NtUserGetDesktopID",
	"NtUserGetDisplayAutoRotationPreferences",
	"NtUserGetDisplayAutoRotationPreferencesByProcessId",
	"NtUserGetDisplayConfigBufferSizes",
	"NtUserGetDpiForMonitor",
	"NtUserGetGestureConfig",
	"NtUserGetGestureExtArgs",
	"NtUserGetGestureInfo",
	"NtUserGetGuiResources",
	"NtUserGetHimetricScaleFactorFromPixelLocation",
	"NtUserGetImeHotKey",
	"NtUserGetImeInfoEx",
	"NtUserGetInputLocaleInfo",
	"NtUserGetInternalWindowPos",
	"NtUserGetKeyNameText",
	"NtUserGetKeyboardLayoutName",
	"NtUserGetLayeredWindowAttributes",
	"NtUserGetListBoxInfo",
	"NtUserGetMenuIndex",
	"NtUserGetMenuItemRect",
	"NtUserGetMouseMovePointsEx",
	"NtUserGetOwnerTransformedMonitorRect",
	"NtUserGetPhysicalDeviceRect",
	"NtUserGetPointerCursorId",
	"NtUserGetPointerDevice",
	"NtUserGetPointerDeviceCursors",
	"NtUserGetPointerDeviceProperties",
	"NtUserGetPointerDeviceRects",
	"NtUserGetPointerDevices",
	"NtUserGetPointerInfoList",
	"NtUserGetPointerInputTransform",
	"NtUserGetPointerType",
	"NtUserGetPrecisionTouchPadConfiguration",
	"NtUserGetPriorityClipboardFormat",
	"NtUserGetProcessDpiAwareness",
	"NtUserGetProcessUIContextInformation",
	"NtUserGetQueueEventStatus",
	"NtUserGetRawInputBuffer",
	"NtUserGetRawInputData",
	"NtUserGetRawInputDeviceInfo",
	"NtUserGetRawInputDeviceList",
	"NtUserGetRawPointerDeviceData",
	"NtUserGetRegisteredRawInputDevices",
	"NtUserGetTopLevelWindow",
	"NtUserGetTouchInputInfo",
	"NtUserGetTouchValidationStatus",
	"NtUserGetUpdatedClipboardFormats",
	"NtUserGetWOWClass",
	"NtUserGetWindowBand",
	"NtUserGetWindowCompositionAttribute",
	"NtUserGetWindowCompositionInfo",
	"NtUserGetWindowDisplayAffinity",
	"NtUserGetWindowFeedbackSetting",
	"NtUserGetWindowMinimizeRect",
	"NtUserGetWindowRgnEx",
	"NtUserGhostWindowFromHungWindow",
	"NtUserHandleDelegatedInput",
	"NtUserHardErrorControl",
	"NtUserHidePointerContactVisualization",
	"NtUserHiliteMenuItem",
	"NtUserHungWindowFromGhostWindow",
	"NtUserHwndQueryRedirectionInfo",
	"NtUserHwndSetRedirectionInfo",
	"NtUserImpersonateDdeClientWindow",
	"NtUserInitTask",
	"NtUserInitialize",
	"NtUserInitializeClientPfnArrays",
	"NtUserInitializeTouchInjection",
	"NtUserInjectGesture",
	"NtUserInjectTouchInput",
	"NtUserInternalClipCursor",
	"NtUserInternalGetWindowIcon",
	"NtUserIsMouseInPointerEnabled",
	"NtUserIsMouseInputEnabled",
	"NtUserIsTopLevelWindow",
	"NtUserIsTouchWindow",
	"NtUserLayoutCompleted",
	"NtUserLinkDpiCursor",
	"NtUserLoadKeyboardLayoutEx",
	"NtUserLockWindowStation",
	"NtUserLockWorkStation",
	"NtUserLogicalToPerMonitorDPIPhysicalPoint",
	"NtUserLogicalToPhysicalPoint",
	"NtUserMNDragLeave",
	"NtUserMNDragOver",
	"NtUserMagControl",
	"NtUserMagGetContextInformation",
	"NtUserMagSetContextInformation",
	"NtUserMenuItemFromPoint",
	"NtUserMinMaximize",
	"NtUserModifyWindowTouchCapability",
	"NtUserNotifyIMEStatus",
	"NtUserOpenInputDesktop",
	"NtUserOpenThreadDesktop",
	"NtUserPaintMonitor",
	"NtUserPerMonitorDPIPhysicalToLogicalPoint",
	"NtUserPhysicalToLogicalPoint",
	"NtUserPrintWindow",
	"NtUserPromoteMouseInPointer",
	"NtUserPromotePointer",
	"NtUserQueryBSDRWindow",
	"NtUserQueryDisplayConfig",
	"NtUserQueryInformationThread",
	"NtUserQueryInputContext",
	"NtUserQuerySendMessage",
	"NtUserRealChildWindowFromPoint",
	"NtUserRealWaitMessageEx",
	"NtUserRegisterBSDRWindow",
	"NtUserRegisterEdgy",
	"NtUserRegisterErrorReportingDialog",
	"NtUserRegisterHotKey",
	"NtUserRegisterPointerDeviceNotifications",
	"NtUserRegisterPointerInputTarget",
	"NtUserRegisterRawInputDevices",
	"NtUserRegisterServicesProcess",
	"NtUserRegisterSessionPort",
	"NtUserRegisterTasklist",
	"NtUserRegisterTouchHitTestingWindow",
	"NtUserRegisterTouchPadCapable",
	"NtUserRegisterUserApiHook",
	"NtUserRemoteConnect",
	"NtUserRemoteRedrawRectangle",
	"NtUserRemoteRedrawScreen",
	"NtUserRemoteStopScreenUpdates",
	"NtUserRemoveClipboardFormatListener",
	"NtUserReportInertia",
	"NtUserResolveDesktopForWOW",
	"NtUserSendEventMessage",
	"NtUserSetActivationFilter",
	"NtUserSetActiveProcess",
	"NtUserSetAppImeLevel",
	"NtUserSetAutoRotation",
	"NtUserSetBrokeredForeground",
	"NtUserSetCalibrationData",
	"NtUserSetChildWindowNoActivate",
	"NtUserSetClassWord",
	"NtUserSetCursorContents",
	"NtUserSetDisplayAutoRotationPreferences",
	"NtUserSetDisplayConfig",
	"NtUserSetDisplayMapping",
	"NtUserSetFallbackForeground",
	"NtUserSetGestureConfig",
	"NtUserSetImeHotKey",
	"NtUserSetImeInfoEx",
	"NtUserSetImeOwnerWindow",
	"NtUserSetImmersiveBackgroundWindow",
	"NtUserSetInternalWindowPos",
	"NtUserSetLayeredWindowAttributes",
	"NtUserSetMenu",
	"NtUserSetMenuContextHelpId",
	"NtUserSetMenuFlagRtoL",
	"NtUserSetMirrorRendering",
	"NtUserSetObjectInformation",
	"NtUserSetPrecisionTouchPadConfiguration",
	"NtUserSetProcessDpiAwareness",
	"NtUserSetProcessRestrictionExemption",
	"NtUserSetProcessUIAccessZorder",
	"NtUserSetShellWindowEx",
	"NtUserSetSysColors",
	"NtUserSetSystemCursor",
	"NtUserSetSystemTimer",
	"NtUserSetThreadInputBlocked",
	"NtUserSetThreadLayoutHandles",
	"NtUserSetWindowBand",
	"NtUserSetWindowCompositionAttribute",
	"NtUserSetWindowCompositionTransition",
	"NtUserSetWindowDisplayAffinity",
	"NtUserSetWindowFeedbackSetting",
	"NtUserSetWindowRgnEx",
	"NtUserSetWindowStationUser",
	"NtUserShowSystemCursor",
	"NtUserShutdownBlockReasonCreate",
	"NtUserShutdownBlockReasonQuery",
	"NtUserShutdownReasonDestroy",
	"NtUserSignalRedirectionStartComplete",
	"NtUserSlicerControl",
	"NtUserSoundSentry",
	"NtUserSwitchDesktop",
	"NtUserTestForInteractiveUser",
	"NtUserTrackPopupMenuEx",
	"NtUserTransformPoint",
	"NtUserTransformRect",
	"NtUserUndelegateInput",
	"NtUserUnloadKeyboardLayout",
	"NtUserUnlockWindowStation",
	"NtUserUnregisterHotKey",
	"NtUserUnregisterSessionPort",
	"NtUserUnregisterUserApiHook",
	"NtUserUpdateDefaultDesktopThumbnail",
	"NtUserUpdateInputContext",
	"NtUserUpdateInstance",
	"NtUserUpdateLayeredWindow",
	"NtUserUpdatePerUserSystemParameters",
	"NtUserUpdateWindowInputSinkHints",
	"NtGdiInit",
	"NtUserUserHandleGrantAccess",
	"NtUserValidateHandleSecure",
	"NtUserWaitAvailableMessageEx",
	"NtUserWaitForInputIdle",
	"NtUserWaitForMsgAndEvent",
	"NtUserWaitForRedirectionStartComplete",
	"NtUserWindowFromPoint",
	"NtValidateCompositionSurfaceHandle",
	"NtUserSetClassLongPtr",
	"NtUserSetWindowLongPtr"
};