#pragma once
#pragma once

#define W32pServiceTableLimit_7601 453

static const char *W32pServiceTableNames_7601[] = {
	"NtAcceptConnectPort"	,													 
	"NtAccessCheck"		,												
	"NtAccessCheckAndAuditAlarm	"	,											 
	"NtAccessCheckByType"		,											 
	"NtAccessCheckByTypeAndAuditAlarm"	,												
	"NtAccessCheckByTypeResultList"	,												 
	"NtAccessCheckByTypeResultListAndAuditAlarm	"	,											 
	"NtAccessCheckByTypeResultListAndAuditAlarmByHandle"	,												
	"NtAcquireCMFViewOwnership",
	"NtAcquireCrossVmMutant",
	"NtAcquireProcessActivityReference",
	"NtAddAtom"								,	
	"NtAddAtomEx",
	"NtAddBootEntry"	,										
	"NtAddDriverEntry"	,												
	"NtAdjustGroupsToken"	,												 
	"NtAdjustPrivilegesToken"	,												
	"NtAdjustTokenClaimsAndDeviceGroups",
	"NtAlertResumeThread"		,										
	"NtAlertThreadByThreadId",
	"NtAllocateLocallyUniqueId"	,												
	"NtAllocateReserveObject"	,												 
	"NtAllocateUserPhysicalPages"	,												
	"NtAllocateUserPhysicalPagesEx",
	"NtAllocateUuids"				,								
	"NtAllocateVirtualMemory"		,												 
	"NtAllocateVirtualMemoryEx",
	"NtAlpcAcceptConnectPort"	,												 
	"NtAlpcCancelMessage"	,												
	"NtAlpcConnectPort"		,										 
	"NtAlpcConnectPortEx",
	"NtAlpcCreatePort"		,											 
	"NtAlpcCreatePortSection"		,												
	"NtAlpcCreateResourceReserve"	,												
	"NtAlpcCreateSectionView"		,											
	"NtAlpcCreateSecurityContext"	,												
	"NtAlpcDeletePortSection"		,											 
	"NtAlpcDeleteResourceReserve"	,													
	"NtAlpcDeleteSectionView"		,											
	"NtAlpcDeleteSecurityContext"	,												
	"NtAlpcDisconnectPort"			,										 
	"NtAlpcImpersonateClientContainerOfPort",
	"NtAlpcImpersonateClientOfPort"		,											 
	"NtAlpcOpenSenderProcess"		,										 
	"NtAlpcOpenSenderThread"		,										
	"NtAlpcQueryInformation"	,											 
	"NtAlpcQueryInformationMessage"		,											
	"NtAlpcRevokeSecurityContext"	,													 
	"NtAlpcSendWaitReceivePort"		,											
	"NtAlpcSetInformation"			,									 
	"NtAreMappedFilesTheSame"		,										 
	"NtAssignProcessToJobObject"	,											
	"NtAssociateWaitCompletionPacket",
	"NtCallEnclave",
	"NtCallbackReturn"		,											
	"NtCancelDeviceWakeupRequest",
	"NtCancelIoFile"		,										 
	"NtCancelIoFileEx"		,										 
	"NtCancelSynchronousIoFile"	,												
	"NtCancelTimer"		,											
	"NtCancelTimer2",
	"NtCancelWaitCompletionPacket",
	"NtClearAllSavepointsTransaction",
	"NtClearEvent"			,											
	"NtClearSavepointTransaction",
	"NtClose"				,										
	"NtCloseObjectAuditAlarm"	,												
	"NtCommitComplete"		,											
	"NtCommitEnlistment"	,												 
	"NtCommitTransaction"	,													
	"NtCompactKeys	"		,										
	"NtCompareTokens"		,											
	"NtCompleteConnectPort"		,											
	"NtCompressKey"		,										
	"NtConnectPort"		,										 
	"NtContinue"		,									
	"NtContinueEx",
	"NtCreateDebugObject"	,											 
	"NtCreateDirectoryObject"	,												
	"NtCreateDirectoryObjectEx",
	"NtCreateEnclave",
	"NtCreateEnlistment"	,													
	"NtCreateEvent"		,								 
	"NtCreateEventPair"		,										
	"NtCreateFile"		,										
	"NtCreateIRTimer",
	"NtCreateIoCompletion"	,											 
	"NtCreateJobObject"			,									 
	"NtCreateJobSet"					,								 
	"NtCreateKey"				,									 
	"NtCreateKeyTransacted"		,											 
	"NtCreateKeyedEvent"		,										
	"NtCreateLowBoxToken",
	"NtCreateMailslotFile"		,											
	"NtCreateMutant"		,									
	"NtCreateNamedPipeFile"		,											 
	"NtCreatePagingFile"	,											 
	"NtCreatePartition",
	"NtCreatePort"			,								 
	"NtCreatePrivateNamespace"	,												
	"NtCreateProcess"		,										 
	"NtCreateProcessEx"		,									 
	"NtCreateProfile"		,										 
	"NtCreateProfileEx"		,										 
	"NtCreateRegistryTransaction",
	"NtCreateResourceManager"	,										 
	"NtCreateSectionEx",
	"NtCreateSemaphore"		,											 
	"NtCreateSymbolicLinkObject"	,												 
	"NtCreateThread	"		,								 
	"NtCreateThreadEx"		,									 
	"NtCreateTimer"		,								
	"NtCreateToken"		,								 
	"NtCreateTokenEx",
	"NtCreateTransaction"	,												 
	"NtCreateTransactionManager",													
	"NtCreateUserProcess"	,									
	"NtCreateWaitablePort"		,										
	"NtCreateWorkerFactory"		,											
	"NtDebugActiveProcess"	,											
	"NtDebugContinue"		,									 
	"NtDelayExecution"	,											
	"NtDeleteAtom"		,										
	"NtDeleteBootEntry"	,											 
	"NtDeleteDriverEntry"	,												 
	"NtDeleteFile"		,									
	"NtDeleteKey"			,							
	"NtDeleteObjectAuditAlarm"		,											 
	"NtDeletePrivateNamespace"	,												 
	"NtDeleteValueKey"			,								
	"NtDeviceIoControlFile"	,												 
	"NtDirectGraphicsCall",
	"NtDisableLastKnownGood"	,												
	"NtDisplayString"	,											 
	"NtDrawText"		,								
	"NtDuplicateObject"		,										 
	"NtDuplicateToken"		,									
	"NtEnableLastKnownGood"		,										
	"NtEnumerateBootEntries"	,											
	"NtEnumerateDriverEntries"		,										
	"NtEnumerateKey"				,				
	"NtEnumerateSystemEnvironmentValuesEx"	,													 
	"NtEnumerateTransactionObject",												 
	"NtEnumerateValueKey"	,										
	"NtExtendSection"		,											
	"NtFilterBootOption",
	"NtFilterToken"		,								  	 
	"NtFilterTokenEx",
	"NtFindAtom"		,								  	 
	"NtFlushBuffersFile"	,										  	 
	"NtFlushBuffersFileEx",
	"NtFlushInstallUILanguage"	,												  	 
	"NtFlushInstructionCache",													  	 
	"NtFlushKey"									  	 ,
	"NtFlushProcessWriteBuffers"	,												  	 
	"NtFlushVirtualMemory"		,									  	 
	"NtFlushWriteBuffer"		,								  	 
	"NtFreeUserPhysicalPages"	,											  	 
	"NtFreeVirtualMemory"	,										  	 
	"NtFreezeRegistry"		,								  	 
	"NtFreezeTransactions"	,											  	 
	"NtFsControlFile"		,								  	 
	"NtGetCachedSigningLevel",
	"NtGetCompleteWnfStateSubscription",
	"NtGetContextThread"		,								  	 
	"NtGetCurrentProcessorNumber" 	, 
	"NtGetCurrentProcessorNumberEx",
	"NtGetDevicePowerState"		,										  	 
	"NtGetMUIRegistryInfo"	,												  	 
	"NtGetNextProcess"		,										  	 
	"NtGetNextThread"		,										  	 
	"NtGetNlsSectionPtr"	,											  	 
	"NtGetNotificationResourceManager"	,												  	 
	"NtGetPlugPlayEvent"	,									  	 
	"NtGetWriteWatch"		,								  	 
	"NtImpersonateAnonymousToken"		,											  	 
	"NtImpersonateClientOfPort"	,											  	 
	"NtImpersonateThread"	,										  	 
	"NtInitializeNlsFiles"	,										  	 
	"NtInitializeRegistry"		,										  	 
	"NtInitiatePowerAction"		,									  	 
	"NtIsProcessInJob"	,									  	 
	"NtIsSystemResumeAutomatic"	,											  	 
	"NtIsUILanguageComitted"	,										  	 
	"NtListenPort"		,											  	 
	"NtLoadDriver"	,											  	 
	"NtLoadKey"	,											  	 
	"NtLoadKey2",
	"NtLoadKeyEx"		,											  	 
	"NtLockFile"	,									  	 
	"NtLockProductActivationKeys"		,											  	 
	"NtLockRegistryKey"			,								  	 
	"NtLockVirtualMemory"		,										  	 
	"NtMakePermanentObject"		,										  	 
	"NtMakeTemporaryObject"		,									  	 
	"NtMapCMFModule",
	"NtMapUserPhysicalPages"	,									  	 
	"NtMapUserPhysicalPagesScatter"	,											  	 
	"NtMapViewOfSection"		,									  	 
	"NtMapViewOfSectionEx",
	"NtMarshallTransaction",
	"NtModifyBootEntry"			,										  	 
	"NtModifyDriverEntry"		,										  	 
	"NtNotifyChangeDirectoryFile"	,												  	 
	"NtNotifyChangeDirectoryFileEx",
	"NtNotifyChangeKey"				,								  	 
	"NtNotifyChangeMultipleKeys"	,												  	 
	"NtNotifyChangeSession"			,										  	 
	"NtOpenDirectoryObject"		,											  	 
	"NtOpenEnlistment"		,										  	 
	"NtOpenEvent"			,								  	 
	"NtOpenEventPair"		,									  	 
	"NtOpenFile"		,							  	 
	"NtOpenIoCompletion"	,										  	 
	"NtOpenJobObject"	,										  	 
	"NtOpenKey"			,						  	 
	"NtOpenKeyEx"			,							  	 
	"NtOpenKeyTransacted"	,											  	 
	"NtOpenKeyTransactedEx"		,										  	 
	"NtOpenKeyedEvent"		,									  	 
	"NtOpenMutant"					,					  	 
	"NtOpenObjectAuditAlarm"	,											  	 
	"NtOpenPartition",
	"NtOpenPrivateNamespace"	,											  	 
	"NtOpenProcess"			,							  	 
	"NtOpenProcessToken	"	,									  	 
	"NtOpenProcessTokenEx"		,										  	 
	"NtOpenRegistryTransaction",
	"NtOpenResourceManager"	,											  	 
	"NtOpenSection"		,								  	 
	"NtOpenSemaphore"	,									  	 
	"NtOpenSession"			,						  	 
	"NtOpenSymbolicLinkObject"	,											  	 
	"NtOpenThread"					,				  	 
	"NtOpenThreadToken"		,								  	 
	"NtOpenThreadTokenEx"	,										  	 
	"NtOpenTimer"			,						  	 
	"NtOpenTransaction"		,								  	 
	"NtOpenTransactionManager"	,											  	 
	"NtPlugPlayControl"		,								  	 
	"NtPowerInformation"	,								 
	"NtPrePrepareComplete"	,										  	 
	"NtPrePrepareEnlistment"	,										  	 
	"NtPrepareComplete"		,								  	 
	"NtPrepareEnlistment"		,									  	 
	"NtPrivilegeCheck"				,						  	 
	"NtPrivilegeObjectAuditAlarm"		,											  	 
	"NtPrivilegedServiceAuditAlarm"		,											  	 
	"NtPropagationComplete"					,					  	 
	"NtPropagationFailed"				,									  	 
	"NtProtectVirtualMemory"			,									  	 
	"NtPssCaptureVaSpaceBulk",
	"NtPullTransaction",
    "NtPulseEvent"				,							  	 
	"NtQueryAttributesFile"			,									  	 
	"NtQueryAuxiliaryCounterFrequency",
	"NtQueryBootEntryOrder"		,									  	 
	"NtQueryBootOptions"		,								  	 
	"NtQueryDebugFilterState"		,										  	 
	"NtQueryDefaultLocale"		,									  	 
	"NtQueryDefaultUILanguage"		,										  	 
	"NtQueryDirectoryFile"		,									  	 
	"NtQueryDirectoryFileEx",
	"NtQueryDirectoryObject"		,										  	 
	"NtQueryDriverEntryOrder"	,												  	 
	"NtQueryEaFile"				,						  	 
	"NtQueryEvent"				,						  	 
	"NtQueryFullAttributesFile"		,											  	 
	"NtQueryInformationAtom"		,										  	 
	"NtQueryInformationByName",
	"NtQueryInformationEnlistment"	,											  	 
	"NtQueryInformationFile"	,									  	 
	"NtQueryInformationJobObject"	,											  	 
	"NtQueryInformationPort"	,									  	 
	"NtQueryInformationProcess"		,									  	 
	"NtQueryInformationResourceManager"	,												  	 
	"NtQueryInformationThread"		,									  	 
	"NtQueryInformationToken"		,									  	 
	"NtQueryInformationTransaction"		,										  	 
	"NtQueryInformationTransactionManager"	,											  	 
	"NtQueryInformationWorkerFactory",													  	 
	"NtQueryInstallUILanguage"	,										  	 
	"NtQueryIntervalProfile",											  	 
	"NtQueryKey"			,					  	 
	"NtQueryLicenseValue"		,										  	 
	"NtQueryMultipleValueKey"	,											  	 
	"NtQueryMutant"				,					  	 
	"NtQueryObject"			,						  	 
	"NtQueryOpenSubKeys"		,							  	 
	"NtQueryOpenSubKeysEx"		,								  	 
	"NtQueryPerformanceCounter"	,										  	 
	"NtQueryPortInformationProcess"	,											  	 
	"NtQueryQuotaInformationFile"	,											  	 
	"NtQuerySection"				,				  	 
	"NtQuerySecurityAttributesToken"	,											  	 
	"NtQuerySecurityObject"	,									  	 
	"NtQuerySecurityPolicy",
	"NtQuerySemaphore"		,							  	 
	"NtQuerySymbolicLinkObject"	,										  	 
	"NtQuerySystemEnvironmentValue"	,											  	 
	"NtQuerySystemEnvironmentValueEx",													  	 
	"NtQuerySystemInformation"		,									  	 
	"NtQuerySystemInformationEx"	,										  	 
	"NtQuerySystemTime"				,					  	 
	"NtQueryTimer"			,					  	 
	"NtQueryTimerResolution"	,									  	 
	"NtQueryValueKey"			,						  	 
	"NtQueryVirtualMemory"		,								  	 
	"NtQueryVolumeInformationFile"	,											  	 
	"NtQueryWnfStateData",
	"NtQueryWnfStateNameInformation",
	"NtQueueApcThread"		,								  	 
	"NtQueueApcThreadEx"	,									  	 
	"NtRaiseException"		,								  	 
	"NtRaiseHardError"	,									  	 
	"NtReadFile"		,						  	 
	"NtReadFileScatter"	,									  	 
	"NtReadOnlyEnlistment"	,										  	 
	"NtReadRequestData"	,									  	 
	"NtReadVirtualMemory"	,										  	 
	"NtRecoverEnlistment"	,									  	 
	"NtRecoverResourceManager"	,										  	 
	"NtRecoverTransactionManager"	,											  	 
	"NtRegisterProtocolAddressInformation",													  	 
	"NtRegisterThreadTerminatePort"	,										  	 
	"NtReleaseCMFViewOwnership",
	"NtReleaseKeyedEvent"		,									  	 
	"NtReleaseMutant"		,								  	 
	"NtReleaseSemaphore"	,									  	 
	"NtReleaseWorkerFactoryWorker"	,												  	 
	"NtRemoveIoCompletion",												  	 
	"NtRemoveIoCompletionEx"	,										  	 
	"NtRemoveProcessDebug",											  	 
	"NtRenameKey"		,								  	 
	"NtRenameTransactionManager",												  	 
	"NtReplaceKey"			,						  	 
	"NtReplacePartitionUnit"	,										  	 
	"NtReplyPort"			,						  	 
	"NtReplyWaitReceivePort"	,										  	 
	"NtReplyWaitReceivePortEx",												  	 
	"NtReplyWaitReplyPort"		,									  	 
	"NtRequestDeviceWakeup",
	"NtRequestPort"				,					  	 
	"NtRequestWaitReplyPort"	,										  	 
	"NtRequestWakeupLatency",
	"NtResetEvent"			,				  	 
	"NtResetWriteWatch"	,								  	 
	"NtRestoreKey"		,						  	 
	"NtResumeProcess"	,								  	 
	"NtResumeThread"	,							  	 
	"NtRevertContainerImpersonation",
	"NtRollbackComplete"		,							  	 
	"NtRollbackEnlistment"		,								  	 
	"NtRollbackRegistryTransaction",
	"NtRollbackSavepointTransaction",
	"NtRollbackTransaction"			,				  	 
	"NtRollforwardTransactionManager"	,											  	 
	"NtSaveKey"			,			  	 
	"NtSaveKeyEx"		,							  	 
	"NtSaveMergedKeys"	,									  	 
	"NtSavepointComplete",
	"NtSavepointTransaction",
	"NtSecureConnectPort"	,											  	 
	"NtSerializeBoot"		,								  	 
	"NtSetBootEntryOrder"		,									  	 
	"NtSetBootOptions",
	"NtSetCachedSigningLevel",
	"NtSetCachedSigningLevel2",
	"NtSetContextThread	"		,								  	 
	"NtSetDebugFilterState"		,									  	 
	"NtSetDefaultHardErrorPort"	,											  	 
	"NtSetDefaultLocale"		,								  	 
	"NtSetDefaultUILanguage"	,										  	 
	"NtSetDriverEntryOrder"		,									  	 
	"NtSetEaFile"				,					  	 
	"NtSetEvent"				,				  	 
	"NtSetEventBoostPriority"	,											  	 
	"NtSetHighEventPair"		,								  	 
	"NtSetHighWaitLowEventPair"	,											  	 
	"NtSetIRTimer",
	"NtSetInformationDebugObject",													  	 
	"NtSetInformationEnlistment",												  	 
	"NtSetInformationFile"		,									  	 
	"NtSetInformationJobObject"	,											  	 
	"NtSetInformationKey"		,									  	 
	"NtSetInformationObject"	,									  	 
	"NtSetInformationResourceManager",													  	 
	"NtSetInformationSymbolicLink",
	"NtSetInformationThread",											  	 
	"NtSetInformationToken"		,									  	 
	"NtSetInformationTransaction"	,											  	 
	"NtSetInformationTransactionManager"	,												  	 
	"NtSetInformationVirtualMemory",
	"NtSetInformationWorkerFactory"	,												  	 
	"NtSetIntervalProfile"		,									  	 
	"NtSetIoCompletion"			,								  	 
	"NtSetIoCompletionEx"		,										  	 
	"NtSetLdtEntries"		,										  	 
	"NtSetLowEventPair"		,									  	 
	"NtSetLowWaitHighEventPair"	,												  	 
	"NtSetQuotaInformationFile"		,										  	 
	"NtSetSystemEnvironmentValue",
	"NtSetSystemEnvironmentValueEx"	,												  	 
	"NtSetSystemInformation",											
	"NtSetSystemPowerState"		,									 
	"NtSetSystemTime"		,									 
	"NtSetThreadExecutionState"		,										 
	"NtSetTimer"		,						 
	"NtSetTimer2",
	"NtSetTimerEx"	,											 
	"NtSetTimerResolution",												 
	"NtSetUuidSeed"		,									 		 
	"NtSetWnfProcessNotificationEvent",
	"NtShutdownSystem"			,							
	"NtShutdownWorkerFactory"	,											 
	"NtSignalAndWaitForSingleObject",												
	"NtSinglePhaseReject"	,											 
	"NtStartProfile"	,										 
	"NtStartTm",
	"NtStopProfile"		,									 
	"NtSubscribeWnfStateChange",
	"NtSuspendProcess"		,										 
	"NtSuspendThread"	,										 
	"NtSystemDebugControl"	,											 
	"NtTerminateEnclave",
	"NtTerminateJobObject",												 
	"NtTerminateProcess",												
	"NtTerminateThread"	,											
	"NtTestAlert"		,									 
	"NtThawRegistry",											
	"NtTraceControl"	,										
	"NtTraceEvent"	,										 
	"NtTranslateFilePath",													
	"NtUmsThreadYield"	,											
	"NtUnloadDriver	"	,										
	"NtUnloadKey"	,										 
	"NtUnloadKey2"	,										
	"NtUnloadKeyEx"	,										 
	"NtUnlockFile"	,										
	"NtUnlockVirtualMemory"	,												 
	"NtUnmapViewOfSection"	,												 													 
	"NtWaitForDebugEvent"	,											 
	"NtWaitForKeyedEvent"	,											
	"NtWaitForMultipleObjects32",													
	"NtWaitForSingleObject"		,									 
	"NtWaitForWnfNotifications",
	"NtWaitForWorkViaWorkerFactory"	,												
	"NtWaitHighEventPair"	,										
	"NtWaitLowEventPair	"	,								 
	"NtWriteFileGather"		,									
	"NtWriteRequestData"	,										
	"NtWriteVirtualMemory"	,											 
	"NtYieldExecution"											 
};
